import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import { CartProvider } from "@/components/cart/cart-context";
import { cookies } from "next/headers";
import { getCart } from "@/lib/shopify";

export const metadata: Metadata = {
  title: "Shopify commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartId = (await cookies()).get("cartId")?.value;
  const cart = getCart(cartId);

  return (
    <html lang="en">
      <body className="antialiased">
        <CartProvider cartPromise={cart}>
          <NavBar />
          <main className="">{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
